<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<strong>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Incidunt necessitatibus aut tempore quas laudantium
    accusantium nam, nemo fugit veniam illo labore dicta qui dolores ex cumque vero officia facere aliquid?
    Dignissimos esse quibusdam error cum, in necessitatibus autem doloribus sed, placeat incidunt facilis voluptate
    porro vel, dolores reprehenderit repellat exercitationem enim libero tempore excepturi temporibus rem ad. Autem,
    inventore? Illum!
    Odio accusantium veniam ut reprehenderit consequatur? Dignissimos explicabo hic velit consequatur ipsa provident,
    minima totam at reiciendis eligendi impedit animi esse modi ullam, officiis neque omnis voluptates amet dolor
    illo.</strong>
