<h1>Table Block</h1>
<?php $employeeData = $this->getInfo(); 
if ($employeeData && count($employeeData) > 0) :
    ?>
        
    <table>
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($employeeData as $employee) : ?>
                <tr>
                    <td><?php echo $employee->getEmployeeId(); ?></td>
                    <td><?php echo $employee->getFirstName(); ?></td>
                    <td><?php echo $employee->getLastName(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php else: ?>
    <p>No employees found.</p>
    <?php endif; ?>