<h1>Table Block</h1>
<?php $employeeData = $this->getInfo();
if ($employeeData && count($employeeData) > 0):
    ?>

    <table>
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email Id</th>
                <th>Address</th>
                <th>Phone Number</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($employeeData as $employee): ?>
                <?php
                $employeeId = $employee->getEmployeeId();
                $deleteRoute = $block->getDeleteUrl() . "$employeeId";
                ?>
                <tr>
                    <td>
                        <?php echo $employeeId; ?>
                    </td>
                    <td>
                        <?php echo $employee->getFirstName(); ?>
                    </td>
                    <td>
                        <?php echo $employee->getLastName(); ?>
                    </td>
                    <td>
                        <?php echo $employee->getEmailId(); ?>
                    </td>
                    <td>
                        <?php echo $employee->getAddress(); ?>
                    </td>
                    <td>
                        <?php echo $employee->getPhoneNumber(); ?>
                    </td>
                    <td>
                        <a href="<?php echo $deleteRoute; ?>">
                            <button>DELETE </button>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>No employees found.</p>
<?php endif; ?>