<h2><?= $block->getSubtitle() ?></h2>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloribus nulla, quod repellat, accusantium harum aliquam quidem laboriosam vero voluptates aliquid molestias deleniti alias repudiandae explicabo sunt dignissimos aperiam atque expedita?
Nihil iste est nisi eligendi fugiat, a aut explicabo tempora minus quaerat facilis eveniet voluptates, neque reprehenderit? Asperiores provident veritatis nobis laborum, distinctio cupiditate repellat, at harum iure officiis hic!
Accusantium rem, impedit dignissimos quod error, quasi aliquid veniam dolor expedita cum quae eveniet dolore non consequatur earum eaque deserunt harum. Alias ab nulla hic aperiam neque impedit praesentium vitae.
Magni necessitatibus autem fugiat, corporis eaque facere accusamus dolore nesciunt odio quo at molestias sit veniam asperiores consequatur voluptate ex dolores, aut quaerat aliquam porro maiores. Nam iure sequi iste.
Consequuntur quaerat sunt ipsum mollitia voluptas esse, sit quisquam illo rerum obcaecati nostrum quod aliquid dicta illum natus non velit consectetur autem. Eos, dolores! Veniam assumenda voluptatibus nesciunt adipisci voluptatum!
Magni, facilis ea eveniet itaque sed dolores quo at, harum ipsam non totam temporibus deserunt necessitatibus, sequi soluta recusandae blanditiis ratione rerum officia minus cupiditate? Recusandae expedita corrupti animi voluptate!
Voluptatum architecto vitae animi fugiat obcaecati iusto iste labore perferendis accusamus exercitationem sequi excepturi distinctio culpa consectetur sunt aspernatur, aliquam rem. Perspiciatis labore expedita animi quidem consequatur molestias, laudantium ratione.
Aperiam aliquid consequatur mollitia odit eligendi. Quisquam libero nisi minima tempora, fuga numquam quae quas mollitia recusandae obcaecati quaerat, labore, est a ratione necessitatibus perferendis cupiditate aperiam nulla ea sequi!
Fugit exercitationem libero neque dolor, quod facere molestias explicabo sed consectetur sapiente consequatur autem eius earum aperiam quidem, officia mollitia incidunt. Eligendi sapiente incidunt praesentium commodi officiis id animi dolore.
Odit architecto aliquid culpa reiciendis suscipit harum eum hic provident, ducimus delectus. Ex hic impedit in obcaecati, qui aut dolores est dolorem nam nesciunt enim voluptatibus sint quos? Rerum, architecto.
Dolor modi repudiandae maiores perspiciatis quia minus reprehenderit sed possimus, excepturi nulla minima, delectus ullam odio tenetur accusamus ducimus corrupti. Earum ad nobis non illum excepturi commodi voluptate repellendus perspiciatis!</p>
<?= $block->getChildHtml('layout_notes')?>
<?= $block->getNodeHtml()?>
above is layout block created on the fly from inside the Index block;